CREATE DATABASE my_store ;
USE my_store;
CREATE TABLE category
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255)  DEFAULT 'Chua Co Ten' ,
	DESCRIPTION TEXT 
);

CREATE TABLE product
(
	ID INT AUTO_INCREMENT PRIMARY KEY ,
	NAME VARCHAR(255)  DEFAULT 'Chua Co Ten',
	PRICE DECIMAL(10,2)  DEFAULT 0,
	DESCRIPTION TEXT,
	IMAGE VARCHAR(255) DEFAULT NULL,
	
	CATEGORYID INT,
	FOREIGN KEY (CATEGORYID) REFERENCES category(ID)
);
	